name: Node CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [8.x, 10.x, 12.x]
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm install
          npm run eslint
          npm run build
        env:
          CI: true
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - run: mkdir -p artifacts/artifact

      - run: echo hello > artifacts/artifact/world.txt

      - uses: actions/upload-artifact@master
        with:
          name: my-first-artifact
          path: artifacts/artifact
